<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "log"
 *
 * Auto generated by Extension Builder 2013-08-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Log',
	'description' => 'Write in the logs in a way that\'s appropriate for this century…',
	'category' => 'plugin',
	'author' => 'Andreas Lappe',
	'author_email' => 'nd@zimmer7.com',
	'author_company' => 'zimmer7',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>